spring:
  application:
    name: event
  datasource:
    url: jdbc:postgresql://localhost:5432/eventdb
    username: eventuser
    password: change_me
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.classic.event.config.LoggingConfig: INFO

event:
  deutsche-oper-berlin:
    url: https://deutscheoperberlin.de/de_DE/event.json
    params:
      search: ""
      id_city_region_search: ""
      category_system: from_file
      category: ""
      location: ""
      status_type: ""
  staatsoper-berlin:
    url: https://www.staatsoper-berlin.de/de/spielplan/_f/%s
