spring:
  application:
    name: event
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.classic.event.config.LoggingConfig: INFO

event:
  deutsche-oper-berlin:
    url: https://deutscheoperberlin.de/de_DE/event.json
    params:
      search: ""
      id_city_region_search: ""
      category_system: from_file
      category: ""
      location: ""
      status_type: ""
  hannover-staatstheater:
    url: https://staatstheater-hannover.de/de_DE/event.json
    params:
      current_page: "kalender"
      current_language: ""
      keyword: ""
      status: ""
      location: "alle"
      category: "alle"
  staatsoper-berlin:
    url: https://www.staatsoper-berlin.de/de/spielplan/_f/%s
  semper-oper-dresden:
    url: https://www.semperoper.de/en/whats-on/calendar/calendar
    type: 1761913461
    action: loadByScroll
    mode: after
